---
openapi: "3.0.1"
info:
  title: "OpenAPI definition"
  version: "v0"
servers:
- url: "http://localhost"
  description: "Generated server url"
paths:
  /api/v1/ocra/verify:
    post:
      tags:
      - "ocra-verification-controller"
      summary: "Verify an OCRA OTP submission"
      description: "Replays an OCRA execution with the supplied OTP and context to\
        \ determine whether the OTP was valid for the referenced credential configuration."
      operationId: "verify"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OcraVerificationRequest"
        required: true
      responses:
        "200":
          description: "Verification completed"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OcraVerificationResponse"
              examples:
                Match:
                  summary: "Successful verification"
                  description: "Match"
                  value:
                    status: "match"
                    reasonCode: "match"
                    metadata:
                      credentialSource: "stored"
                      suite: "OCRA-1:HOTP-SHA256-8:QA08-S064"
                      otpLength: 8
                      durationMillis: 11
                      contextFingerprint: "Base64URL-Hash"
                      telemetryId: "rest-ocra-verify-<uuid>"
                      outcome: "match"
        "500":
          description: "Unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OcraVerificationErrorResponse"
        "422":
          description: "Verification payload failed validation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OcraVerificationErrorResponse"
              examples:
                Missing context:
                  summary: "Validation failure"
                  description: "Missing context"
                  value:
                    error: "invalid_input"
                    message: "sessionHex is required"
                    details:
                      telemetryId: "rest-ocra-verify-<uuid>"
                      status: "invalid"
                      suite: "OCRA-1:HOTP-SHA256-8:QA08-S064"
                      field: "sessionHex"
                      reasonCode: "session_required"
                      sanitized: "true"
        "404":
          description: "Credential not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OcraVerificationErrorResponse"
  /api/v1/ocra/evaluate:
    post:
      tags:
      - "ocra-evaluation-controller"
      summary: "Evaluate an OCRA request"
      description: "Computes an OCRA OTP for the supplied suite and runtime parameters."
      operationId: "evaluate"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OcraEvaluationRequest"
        required: true
      responses:
        "400":
          description: "Invalid request payload"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OcraEvaluationErrorResponse"
              examples:
                Missing session payload:
                  summary: "Validation failure with reason code"
                  description: "Missing session payload"
                  value:
                    error: "invalid_input"
                    message: "sessionHex is required for the requested suite"
                    details:
                      telemetryId: "rest-ocra-<uuid>"
                      status: "invalid"
                      suite: "OCRA-1:HOTP-SHA256-8:QA08-S064"
                      field: "sessionHex"
                      reasonCode: "session_required"
                      sanitized: "true"
        "200":
          description: "Evaluation successful"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OcraEvaluationResponse"
        "500":
          description: "Unexpected server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OcraEvaluationErrorResponse"
  /api/v1/ocra/credentials/seed:
    post:
      tags:
      - "ocra-credential-directory-controller"
      operationId: "seedCredentials"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SeedResponse"
  /api/v1/ocra/credentials:
    get:
      tags:
      - "ocra-credential-directory-controller"
      operationId: "listCredentials"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/OcraCredentialSummary"
components:
  schemas:
    OcraVerificationContext:
      type: "object"
      properties:
        challenge:
          type: "string"
        clientChallenge:
          type: "string"
        serverChallenge:
          type: "string"
        sessionHex:
          type: "string"
        timestampHex:
          type: "string"
        counter:
          type: "integer"
          format: "int64"
        pinHashHex:
          type: "string"
    OcraVerificationInlineCredential:
      type: "object"
      properties:
        suite:
          type: "string"
        sharedSecretHex:
          type: "string"
    OcraVerificationRequest:
      type: "object"
      properties:
        otp:
          type: "string"
        credentialId:
          type: "string"
        inlineCredential:
          $ref: "#/components/schemas/OcraVerificationInlineCredential"
        context:
          $ref: "#/components/schemas/OcraVerificationContext"
    OcraVerificationMetadata:
      type: "object"
      properties:
        credentialSource:
          type: "string"
        mode:
          type: "string"
        suite:
          type: "string"
        otpLength:
          type: "integer"
          format: "int32"
        durationMillis:
          type: "integer"
          format: "int64"
        contextFingerprint:
          type: "string"
        telemetryId:
          type: "string"
        outcome:
          type: "string"
    OcraVerificationResponse:
      type: "object"
      properties:
        status:
          type: "string"
        reasonCode:
          type: "string"
        metadata:
          $ref: "#/components/schemas/OcraVerificationMetadata"
    OcraVerificationErrorResponse:
      type: "object"
      properties:
        error:
          type: "string"
        message:
          type: "string"
        details:
          type: "object"
          additionalProperties:
            type: "object"
    OcraEvaluationRequest:
      type: "object"
      properties:
        credentialId:
          type: "string"
        suite:
          type: "string"
        sharedSecretHex:
          type: "string"
        challenge:
          type: "string"
        sessionHex:
          type: "string"
        clientChallenge:
          type: "string"
        serverChallenge:
          type: "string"
        pinHashHex:
          type: "string"
        timestampHex:
          type: "string"
        counter:
          type: "integer"
          format: "int64"
    OcraEvaluationErrorResponse:
      type: "object"
      properties:
        error:
          type: "string"
        message:
          type: "string"
        details:
          type: "object"
          additionalProperties:
            type: "string"
    OcraEvaluationResponse:
      type: "object"
      properties:
        suite:
          type: "string"
        otp:
          type: "string"
        telemetryId:
          type: "string"
    SeedResponse:
      type: "object"
      properties:
        addedCount:
          type: "integer"
          format: "int32"
        canonicalCount:
          type: "integer"
          format: "int32"
        addedCredentialIds:
          type: "array"
          items:
            type: "string"
    OcraCredentialSummary:
      type: "object"
      properties:
        id:
          type: "string"
        label:
          type: "string"
        suite:
          type: "string"
