name: Secret Scanning

on:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --redact --verbose
